apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-apps
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default

  sources:
    - repoURL: {{ .Values.deployment.oss.repository.URL }}
      targetRevision: {{ .Values.deployment.oss.repository.branch }}
      path: "{{ .Values.deployment.oss.repository.baseDir }}/{{ .Values.deployment.oss.repository.appsDir }}"
      helm:
        values: |
          {{ omit .Values "argo-cd" | toYaml | nindent 10 }}

  destination:
    name: in-cluster
    namespace: argocd

  syncPolicy:
    retry:
      limit: 5
      backoff:
        duration: 15s
        factor: 2
        maxDuration: 30m
    automated:
      prune: true
      selfHeal: true
