
registerJob:
  enabled: true
  image:
    registry: ghcr.io/flamingo-stack/registry
    repository: curlimages/curl
    tag: "8.9.1"


server:
  image:
    registry: ghcr.io/flamingo-stack/openframe-oss-tenant
    repository: meshcentral
    tag: latest
  podAnnotations:
    loki.grafana.com/scrape: "true"
    prometheus.io/scrape: "true"
    prometheus.io/port: "8383"
    prometheus.io/path: "/metrics"

  initImage:
    registry: ghcr.io/flamingo-stack/registry
    repository: busybox
    tag: "1.36.0"
  waitMongodbImage:
    registry: ghcr.io/flamingo-stack/registry
    repository: mongo
    tag: "8.0.9"
