deployment:
  oss:
    enabled: true    
    repository:
      branch: main
      profile: dev

registerJob:
  enabled: true
  image:
    registry: ghcr.io/flamingo-stack/registry
    tag: "8.9.1"

image:
  repo: ghcr.io/flamingo-stack/openframe-oss-tenant/openframe-config
  tag: latest
