deployment:
  oss:
    enabled: true    
    repository:
      profile: dev

registerJob:
  enabled: true
  image:
    registry: ghcr.io/flamingo-stack/registry
    tag: "8.9.1"

initContainer:
  image:
    registry: ghcr.io/flamingo-stack/registry
    tag: "8.9.1"

image:
  repo: ghcr.io/flamingo-stack/openframe-oss-tenant/openframe-stream
  tag: latest

service:
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8083"
    prometheus.io/path: "/management/v1/prometheus"
