global:
  image:
    tag: latest

registerJob:
  enabled: true
  image:
    registry: ghcr.io/flamingo-stack/registry
    repository: curlimages/curl
    tag: "8.9.1"

mongoExpress:

  image:
    registry: ghcr.io/flamingo-stack/registry
    repository: mongo-express
    tag: "1.0.2"
  podAnnotations:
    loki.grafana.com/scrape: "true"
