apiVersion: v2
name: alloy-wrapper
description: Wrapper chart for Grafana Alloy
type: application
version: 0.0.1
appVersion: "0.0.1"

dependencies:
  - name: alloy
    version: "~1.5.0"
    repository: https://grafana.github.io/helm-charts
