global:
  image:
    tag: latest

registerJob:
  enabled: true
  image:
    registry: ghcr.io/flamingo-stack/registry
    repository: curlimages/curl
    tag: "8.9.1"

telepresence-oss:
  logLevel: info

  image:
    registry: ghcr.io/flamingo-stack/registry/telepresenceio
    name: tel2
    tag: "2.25.1"
  podAnnotations:
    loki.grafana.com/scrape: "true"

  hooks:
    busybox:
      registry: ghcr.io/flamingo-stack/registry
      image: busybox
      tag: "1.36"

    curl:
      registry: ghcr.io/flamingo-stack/registry
      image: curlimages/curl
      tag: "8.9.1"
