
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openframe-config
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: openframe-config
  template:
    metadata:
      labels:
        app: openframe-config
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        prometheus.io/port: "8889"
        prometheus.io/path: "/management/{{ .Values.global.image.tag }}/prometheus"
    spec:

      containers:
        - name: openframe-config
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ default .Values.image.tag .Values.global.image.tag }}"
          ports:
            - containerPort: 8888
              name: http
            - containerPort: 8889
              name: management
          envFrom:
            - configMapRef:
                name: microservices
            - configMapRef:
                name: openframe-config

          resources:
            {{- toYaml .Values.resources | nindent 12 }}

          livenessProbe:
            httpGet:
              path: /xml/shared-logback-spring.xml
              port: http
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /xml/shared-logback-spring.xml
              port: http
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 5
