apiVersion: v1
kind: Service
metadata:
  name: openframe-config
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    app: openframe-config
spec:
  selector:
    app: openframe-config
  ports:
    - port: 8888
      targetPort: 8888
      name: http
    - port: 8889
      targetPort: 8889
      name: management
  type: ClusterIP
