environment: dev

deployment:
  oss:
    repository:
      profile: dev

registerJob:
  enabled: true
  image:
    registry: ghcr.io/flamingo-stack/registry
    tag: "8.9.1"
servicemonitor:
  enabled: true

image:
  repo: ghcr.io/flamingo-stack/openframe-oss-tenant/openframe-authorization-server
  tag: latest

initContainer:
  image:
    registry: ghcr.io/flamingo-stack/registry
    tag: "8.9.1"