apiVersion: apps/v1
kind: Deployment
metadata:
  name: openframe-authorization-server
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: openframe-authorization-server
  template:
    metadata:
      labels:
        app: openframe-authorization-server
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        prometheus.io/port: "9006"
        prometheus.io/path: "/management/{{ .Values.global.image.tag }}/prometheus"

    spec:
      initContainers:
        - name: wait-for-management-server
          image: "{{ .Values.initImage.registry }}/{{ .Values.initImage.repository }}:{{ .Values.initImage.tag }}"
          command: ["sh", "-c", "until curl -f http://openframe-management.microservices.svc.cluster.local:8096/management/{{ .Values.global.image.tag }}/health; do sleep 1; done"]
          
      containers:
        - name: openframe-authorization-server
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ default .Values.image.tag .Values.global.image.tag }}"
          ports:
            - containerPort: 9005
              name: http
            - containerPort: 9006
              name: management
          env:
            {{- if .Values.deployment.oss.ingress.ngrok.enabled }}
            - name: TENANT_HOST_URL
              value: {{ printf "https://%s" (required "deployment.oss.ingress.ngrok.url is required when ngrok ingress is enabled" .Values.deployment.oss.ingress.ngrok.url) | quote }}
            {{- else if .Values.deployment.oss.ingress.localhost.enabled }}
            - name: TENANT_HOST_URL
              value: "https://localhost"
            {{- end }}
          envFrom:
            - configMapRef:
                name: microservices

          resources:
            {{- toYaml .Values.resources | nindent 12 }}

          livenessProbe:
            httpGet:
              path: /management/{{ .Values.global.image.tag }}/health
              port: management
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /management/{{ .Values.global.image.tag }}/health
              port: management
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 5
