apiVersion: apps/v1
kind: Deployment
metadata:
  name: openframe-management
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: openframe-management
  template:
    metadata:
      labels:
        app: openframe-management
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        prometheus.io/port: "8096"
        prometheus.io/path: "/management/{{ .Values.global.image.tag }}/prometheus"

    spec:
      initContainers:
        - name: wait-for-config-server
          image: "{{ .Values.initImage.registry }}/{{ .Values.initImage.repository }}:{{ .Values.initImage.tag }}"
          command: ["sh", "-c", "until curl -f http://openframe-config.microservices.svc.cluster.local:8888/xml/shared-logback-spring.xml; do sleep 1; done"]

      containers:
        - name: openframe-management
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ default .Values.image.tag .Values.global.image.tag }}"
          ports:
            - containerPort: 8095
              name: http
            - containerPort: 8096
              name: management
          env:
            {{- if .Values.deployment.oss.ingress.ngrok.enabled }}
            - name: TENANT_HOST_URL
              value: {{ printf "https://%s" (required "deployment.oss.ingress.ngrok.url is required when ngrok ingress is enabled" .Values.deployment.oss.ingress.ngrok.url) | quote }}
            {{- else if .Values.deployment.oss.ingress.localhost.enabled }}
            - name: TENANT_HOST_URL
              value: "https://localhost"
            {{- end }}
          envFrom:
            - configMapRef:
                name: microservices

          resources:
            {{- toYaml .Values.resources | nindent 12 }}

          livenessProbe:
            httpGet:
              path: /management/{{ .Values.global.image.tag }}/health
              port: management
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /management/{{ .Values.global.image.tag }}/health
              port: management
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 5
