apiVersion: v1
kind: Service
metadata:
  name: openframe-management
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    app: openframe-management
spec:
  selector:
    app: openframe-management
  ports:
    - port: 8095
      targetPort: 8095
      name: http
    - port: 8096
      targetPort: 8096
      name: management
  type: ClusterIP
