apiVersion: v1
kind: Service
metadata:
  name: authentik-redis
spec:
  clusterIP: None
  selector:
    app: authentik-redis
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
    protocol: TCP
  {{- if .Values.redis.metrics.enabled }}
  - name: metrics
    port: 9121
    targetPort: 9121
    protocol: TCP
  {{- end }}
