apiVersion: v2
name: kube-prometheus-wrapper
description: Wrapper chart for Prometheus Community kube-prometheus-stack
type: application
version: 0.0.1
appVersion: "0.0.1"

dependencies:
  - name: kube-prometheus-stack
    version: "~79.7.1"
    repository: oci://ghcr.io/flamingo-stack/registry/helm-charts
