apiVersion: v2
name: prometheus-wrapper
description: Wrapper chart for standalone Prometheus
type: application
version: 0.0.1
appVersion: "0.0.1"

dependencies:
  - name: prometheus
    version: "~27.50.0"
    repository: https://prometheus-community.github.io/helm-charts
