apiVersion: v1
kind: Service
metadata:
  name: openframe-stream
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    app: openframe-stream
spec:
  selector:
    app: openframe-stream
  ports:
    - port: 8082
      targetPort: 8082
      name: http
    - port: 8083
      targetPort: 8083
      name: management
  type: ClusterIP
