registerJob:
  enabled: true
  image:
    registry: ghcr.io/flamingo-stack/registry
    tag: "8.9.1"

initContainer:
  image:
    registry: ghcr.io/flamingo-stack/registry
    tag: "8.9.1"

image:
  repo: ghcr.io/flamingo-stack/openframe-oss-tenant/openframe-api
  tag: latest

podAnnotations:
  loki.grafana.com/scrape: "true"
service:
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8091"
    prometheus.io/path: "/management/v1/prometheus"
