registerJob:
  enabled: true
  image:
    registry: ghcr.io/flamingo-stack/registry
    repository: curlimages/curl
    tag: "8.9.1"


mongodb:
  image:
    registry: ghcr.io/flamingo-stack/registry
    repository: mongo
    tag: "8.0.9"
  initImage:
    registry: ghcr.io/flamingo-stack/registry
    repository: busybox
    tag: "1.36.0"
  podAnnotations:
    loki.grafana.com/scrape: "true"
    prometheus.io/scrape: "true"
    prometheus.io/port: "9216"
    prometheus.io/path: "/metrics"

  metrics:
    enabled: true
    image:
      registry: ghcr.io/flamingo-stack/registry
      repository: bitnamilegacy/mongodb-exporter
      tag: "0.46.0"
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 128Mi