apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: fleetmdm-server
spec:
  serviceName: fleetmdm-server
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: fleetmdm-server
  template:
    metadata:
      labels:
        app: fleetmdm-server
      {{- with .Values.server.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      priorityClassName: fleetmdm

      initContainers:
      - name: wait
        image: "{{ .Values.server.image.registry }}/{{ .Values.server.image.repository }}:{{ .Values.server.image.tag }}"
        command:
        - /bin/sh
        - -c
        - |
          (until nc -z $FLEET_MYSQL_HOST $FLEET_MYSQL_PORT; do sleep 2; done) &
          (until nc -z $REDIS_HOST $REDIS_PORT; do sleep 2; done) &
          wait
          echo "MySQL and Redis are ready."
        envFrom:
        - configMapRef:
            name: fleetmdm-mysql
        - configMapRef:
            name: fleetmdm-redis

      containers:
      - name: fleetmdm
        image: "{{ .Values.server.image.registry }}/{{ .Values.server.image.repository }}:{{ .Values.server.image.tag }}"
        ports:
        - containerPort: 8070
        envFrom:
        - configMapRef:
            name: fleetmdm-server
        - secretRef:
            name: fleetmdm-server
        env:
        - name: FLEET_MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: fleetmdm-mysql
              key: MYSQL_DATABASE
        - name: FLEET_MYSQL_USERNAME
          valueFrom:
            configMapKeyRef:
              name: fleetmdm-mysql
              key: MYSQL_USER
        - name: FLEET_MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: fleetmdm-mysql
              key: MYSQL_PASSWORD
        livenessProbe:
          httpGet:
            path: /setup
            port: 8070
          initialDelaySeconds: 60
          periodSeconds: 15
        volumeMounts:
        - name: fleet-logs
          mountPath: /var/log/osquery

  volumeClaimTemplates:
  - metadata:
      name: fleet-logs
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
