apiVersion: v1
kind: Secret
metadata:
  name: nats-credentials
type: Opaque
stringData:
  ADMIN_USER: "admin"
  ADMIN_PASS: "admin_password"
  DEVICE_USER: "machine"
  SERVICE_USER: "service"
  SERVICE_PASS: "service_pass"
