deployment:
  oss:
    enabled: true    
    repository:
      profile: dev
    ingress:
      localhost:
        enabled: true
      ngrok:
        enabled: false 

registerJob:
  enabled: true
  image:
    registry: ghcr.io/flamingo-stack/registry
    tag: "8.9.1"

initContainer:
  image:
    registry: ghcr.io/flamingo-stack/registry
    tag: "8.9.1"

image:
  repo: ghcr.io/flamingo-stack/openframe-oss-tenant/openframe-management
  tag: latest

service:
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8096"
    prometheus.io/path: "/management/v1/prometheus"
