global:
  image:
    tag: latest

deployment:
  oss:
    ingress:
      localhost:
        enabled: true
      ngrok:
        enabled: false

registerJob:
  enabled: true
  image:
    registry: ghcr.io/flamingo-stack/registry
    repository: curlimages/curl
    tag: "8.9.1"

initImage:
  registry: ghcr.io/flamingo-stack/registry
  repository: curlimages/curl
  tag: "8.9.1"

image:
  registry: ghcr.io/flamingo-stack/openframe-oss-tenant
  repository: openframe-management
  tag: latest

resources:
  requests:
    cpu: "250m"
    memory: "512Mi"
  limits:
    cpu: "500m"
    memory: "1Gi"

podAnnotations:
  loki.grafana.com/scrape: "true"
  prometheus.io/scrape: "true"
