apiVersion: v1
kind: Service
metadata:
  name: fleetmdm-mysql
spec:
  clusterIP: None
  selector:
    app: fleetmdm-mysql
  ports:
  - name: mysql
    port: 3306
    targetPort: 3306
    protocol: TCP
  {{- if .Values.mysql.metrics.enabled }}
  - name: metrics
    port: 9104
    targetPort: 9104
    protocol: TCP
  {{- end }}
