global:
  image:
    tag: latest

registerJob:
  enabled: true
  image:
    registry: ghcr.io/flamingo-stack/registry
    repository: sap/kubectl-container
    tag: "v1.31.6"


tactical:
  frontend:
    image:
      registry: ghcr.io/flamingo-stack/openframe-oss-tenant
      repository: tactical-frontend
      tag: latest
    podAnnotations:
      loki.grafana.com/scrape: "true"
      prometheus.io/scrape: "true"
      prometheus.io/port: "8080"
      prometheus.io/path: "/metrics"


  nginx:
    image:
      registry: ghcr.io/flamingo-stack/openframe-oss-tenant
      repository: tactical-nginx
      tag: latest
    podAnnotations:
      loki.grafana.com/scrape: "true"
      prometheus.io/scrape: "true"
      prometheus.io/port: "8080"
      prometheus.io/path: "/metrics"


  base:
    image:
      registry: ghcr.io/flamingo-stack/openframe-oss-tenant
      repository: tactical-base
      tag: latest
    podAnnotations:
      loki.grafana.com/scrape: "true"
      prometheus.io/scrape: "true"
      prometheus.io/port: "8000"
      prometheus.io/path: "/metrics"

    initImage:
      registry: ghcr.io/flamingo-stack/registry
      repository: busybox
      tag: "1.36.0"
    waitRedisImage:
      registry: ghcr.io/flamingo-stack/registry
      repository: redis
      tag: "6.0-alpine"
    waitPostgresImage:
      registry: ghcr.io/flamingo-stack/registry
      repository: postgres
      tag: "14-alpine"
