global:
  image:
    tag: latest

deployment:
  oss:
    ingress:
      localhost:
        enabled: true   # Enable localhost ingress with nginx
      ngrok:
        enabled: false  # Enable ngrok ingress for external access
        credentials:
          apiKey: ""
          authtoken: ""
    repository:
      baseDir: manifests
      appsDir: apps
      URL: https://github.com/flamingo-stack/openframe-oss-tenant.git
      branch: main
      autoSync: true

registerJob:
  enabled: true
  image:
    registry: ghcr.io/flamingo-stack/registry
    repository: curlimages/curl
    tag: "8.9.1"

image:
  registry: ghcr.io/flamingo-stack/openframe-oss-tenant
  repository: openframe-frontend
  tag: latest

resources:
  requests:
    cpu: "250m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

podAnnotations:
  loki.grafana.com/scrape: "true"
