registerJob:
  enabled: true
  image:
    registry: ghcr.io/flamingo-stack/registry
    tag: "8.9.1"


redis:
  global:
    security:
      allowInsecureImages: true  # bitnamilegacy

  image:
    registry: ghcr.io/flamingo-stack/registry
    repository: bitnamilegacy/redis
    tag: 8.2.1-debian-12-r0

  auth:
    enabled: false
  
  master:
    revisionHistoryLimit: 2
  
  replica:
    replicaCount: 1
    revisionHistoryLimit: 2

  metrics:
    enabled: true
    image:
      registry: ghcr.io/flamingo-stack/registry
      repository: bitnamilegacy/redis-exporter
      tag: 1.76.0-debian-12-r0
    podAnnotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "9121"
      prometheus.io/path: "/metrics"
