global:
  image:
    tag: latest

registerJob:
  enabled: true
  image:
    registry: ghcr.io/flamingo-stack/registry
    repository: sap/kubectl-container
    tag: "v1.31.6"


server:
  image:
    registry: ghcr.io/flamingo-stack/openframe-oss-tenant
    repository: fleetmdm
    tag: latest
  podAnnotations:
    loki.grafana.com/scrape: "true"
    prometheus.io/scrape: "true"
    prometheus.io/port: "8070"
    prometheus.io/path: "/metrics"
