apiVersion: v1
kind: Service
metadata:
  name: tactical-postgres
spec:
  clusterIP: None
  selector:
    app: tactical-postgres
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
    protocol: TCP
  {{- if .Values.postgres.metrics.enabled }}
  - name: metrics
    port: 9187
    targetPort: 9187
    protocol: TCP
  {{- end }}
