apiVersion: v1
kind: Secret
metadata:
  name: kafka-kraft
type: Opaque
stringData:
  cluster-id: "{{ .Values.deployment.saas.ingress.gcp.tenantID }}"
  controller-0-id: "{{ .Values.deployment.saas.ingress.gcp.tenantID }}-0"